language: python
os:
  - linux
python:
    - "2.7"
    - "3.6"

before_install:
  - mkdir -p ${TRAVIS_BUILD_DIR}/Downloads

  # Download and install Julia 1.0.1
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then \
      curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.1-linux-x86_64.tar.gz -o "${TRAVIS_BUILD_DIR}/Downloads/julia.tar.gz"; \
      tar xzf "${TRAVIS_BUILD_DIR}/Downloads/julia.tar.gz" -C "${TRAVIS_BUILD_DIR}/Downloads"; \
      cp -r "$(find "${TRAVIS_BUILD_DIR}/Downloads" -maxdepth 2 -name "julia*" -type d | head -n 1)" "${TRAVIS_BUILD_DIR}/julia"; \
    fi

  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then \
      curl -L https://julialang-s3.julialang.org/bin/mac/x64/1.0/julia-1.0.1-mac64.dmg -o "${TRAVIS_BUILD_DIR}/Downloads/julia.dmg"; \
      hdiutil attach ${TRAVIS_BUILD_DIR}/Downloads/julia.dmg; \
      cp -r /Volumes/Julia*/Julia*/Contents/Resources/julia ${TRAVIS_BUILD_DIR}/julia; \
      hdiutil detach -force /Volumes/Julia*; \
    fi

  - rm -rf ${TRAVIS_BUILD_DIR}/Downloads/julia*
  - export PATH="${TRAVIS_BUILD_DIR}/julia/bin:$PATH"

  - pip install --quiet tox-travis
script:
  # Create an environment first so that we know what to use for $PYTHON:
  - tox --notest

  # PyCall needs to know the right Python executable to use:
  - export PYTHON="$(echo ${TRAVIS_BUILD_DIR}/.tox/py*/bin/python)" && echo "$PYTHON"

  - tox -- --cov misppy
